### ISSUE TITLE
Output - inhoud

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-vislexdec-vp#11]
Wbt inhoud van de output:

- wat nu 'condition' wordt genoemd is geen condition maar group/list. (word_type is wat we conditie noemen)
-  rt is null, daar moet de reactietijd komen
-  stimulus inderdaad graag zonder html-tags
-  wat is time-elapsed precies? het valt me op dat als ik op geen enkele knop druk en het experiment gewoon laat lopen, het verschil tussen bijvoorbeeld de time_elapased voor prime snow, en de time-elapsed voor bijbehorende target white, orde-grootte 5000 flupsels (wat is de eenheid?) bedraagt. ik snap niet goed waar ik naar kijk dan. er zou 80ms moeten zitten tussen aanbieden prime en target. Ik krijg voor snow hier bijv. 80916, en voor white dan 85920. Kan er geen chocola van maken. Het loopt op over het hele experiment, dus dan zou je denken tijd vanaf begin van het experiment, maar de sprongen tussen prime en target zijn daar veel te groot voor.
-  presented_prime vs word_presented: presented mag weg, of als daar bezwaar tegen is, graag van presented_prime prime_presented maken.
- id_presented ontbreekt bij de prime

**Comment by jcvanelst** [comment]
## wat nu 'condition' wordt genoemd is geen condition maar group/list. (word_type is wat we conditie noemen) <kbd>V</kbd> 

### rt is null, daar moet de reactietijd komen 
Is niet waar, verschilt per type output en trial fase <kbd>V</kbd> 

### wat is time-elapsed precies? 
jsPsych's eigen klokje voor plugins en alles wat het doet.
https://www.jspsych.org/plugins/overview/ ter hoogte van Data collected by plugins (https://www.jspsych.org/plugins/overview/)

standaard aanwezig:

Name | Type | Value
-- | -- | --
trial_type | string | The name of the plugin used to run the trial.
trial_index | numeric | The index of the current trial across the whole experiment.
time_elapsed | numeric | The number of milliseconds since the start of the experiment when the trial ended.
internal_node_id | string | A string identifier for the current TimelineNode.

### presented_prime vs word_presented: presented mag weg, of als daar bezwaar tegen is, graag van presented_prime prime_presented maken. 
<kbd>V</kbd>

### id_presented ontbreekt bij de prime
<kbd>V</kbd>

**Comment by jcvanelst** [comment]
Als ik iets gemist, heb, kan ie weer aan, toch? Ik vind issues sluiten topwerk, namelijk

**Comment by irisopgithub** [comment]
kun je me uitleggen wat er gebeurt met de time_elapsed in mijn voorbeeld? want ik zou inderdaad ook denken dat dat is "The number of milliseconds since the start of the experiment when the trial ended.". maar de getallen die ik krijg snap ik dan dus niet. 

(kan met mijn (gebrek aan) begrip van het concept trial in jsPsych te maken hebben)

**Comment by jcvanelst** [comment]
ik ga proberen je case te reproduceren en de time_elapsed variabele met een minimaal voorbeeld duidelijker te krijgen.

**Comment by irisopgithub** [comment]
na overleg vandaag verzoek om een toevoeging: niet alleen de key value van het gegeven antwoord (77/99), maar ook welke letter dat is (z/m).

**Comment by jcvanelst** [comment]
Dit alles is imiddels niet meer heel actueel. Ik krijg de case van Iris niet gereproduceerd en zou persoonlijk voorstander zijn van het loslaten van de precieze info vraag over time elapsed, voor nu. 

Voorts is met hulp van Ty's commit https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/commit/60ea7f0e3a1ba1d1661ef254f52a800c1b627c88 mogelijk gemnaakt dat een toets op basis van survey info over hand preference EN survey info over toetsenbord-layout kan worden geconfigureerd (linkshandigen krijgen een toets aan de linkerkant als "YES", rechtshandigen aan de rechterkant, dus (Z en M  worden A en L gegeven QWERTY layout) A = linkerkant, L is rechterkant toets en de survey info levert op welke toets welke functie krijgt, gegeven Lexical Decision taken en binaire responses... Dit maakt in principe ook een van de jspsych (hard) concessions een non-concessie (https://github.com/UiL-OTS-labs/jspsych-concessions). 

Met commit https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/commit/11032451c91542294ceaa543867ace38997b0ea3 worden de keys voor ascii karakters geintroduceert en met commit   https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/commit/02bfcba4b9208747ec8b1717ec5a5473aebf4e4a word dit met een werkende toets validatie loop geimplementeerd, zodat het ook in de output staat. Ik sluit deze issue, mocht er iets niet okay zijn, dan graag een nieuwe, gebaseerd op recentere test, voor het overzicht, als dat kan?
